### ISSUE TITLE
UCAB - Automatical Screenshot without button press

### ISSUE THREAD

**Issue by Gelegenheitscode** [rettichlp/UnicacityAddon-1.12.2#103]
**Beschreibe den Bug oder Fehler**
Ich gehe auf den Server und bei jedem Knopf den ich drücke macht sich automatisch ein Screenshot, unabhängig welchen Knopf ich drücke.

**Wie kann der Bug oder Fehler reproduziert werden?**
Schritte zum Reproduzieren des Verhaltens:
1. Unicacity Addon 1.2.0-dev reinnehmen
2. Auf Server joinen
3. Knopf drücken
4. Dort ist der Fehler

**Erwartetes Verhalten**
Macht nur einen Screenshot bei Tastenbetätigung.

**Screenshots**
/

**Weitere Informationen (bitte ausfüllen):**
Minecraft Version: `1.12.2`
Addon Version: `1.2.0-dev`

**Comment by rettichlp** [comment]
Dev version 😉, aber danke für den Tipp

**Comment by Dimiikou** [comment]
fixed in https://github.com/rettichlp/UnicacityAddon-1.12.2/commit/9734128320b744ad241c17728fd0554698322945
