### ISSUE TITLE
UCAF - Implementation of Crystension features

### ISSUE THREAD

**Issue by Dimiikou** [rettichlp/UnicacityAddon-1.12.2#108]
**Aus welchem Grund ist die Idee oder Erweiterung hilfreich?**
Crystension ist ebenfalls eine häufig genutzte und gesehene Mod.
Um das installieren von dieser überflüssig zu machen (da Teile von Crystension noch auf UCUtils Daten zurückgreifen) wäre es Sinnvoll die meist genutzten Features zu übernehmen (mit optimiertem Code)

**Was soll passieren, wie soll die Idee oder Erweiterung umgesetzt werden?**
- [x] /eigenbedarf
- [x] /gifteigenbedarf
- [x] /adropmoney
- [x] /reichensteuer
- [x] /einzahlen
- [x] Karma Anzahl hinter + / - Karma nachricht
- [x] Veränderte HQ Nachrichten

**Sonstiges**
/eigenbedarf - Gibt eine in der Config eingestellte Menge an Drogen als Eigenbedarf an den Spieler
/gifteigenbedarf - verkauft diesen Eigenbedarf für 0$ an Member, welche Rang 2 noch nicht erreicht haben
/adropmoney - Bucht zuerst 15.000$ von einem ATM ab, führt /dropmoney aus und zahlt das Geld wieder ein. (Job automatisierung)
/reichensteuer - Bucht sämtliches Geld über 100.000 automatisch vom Konto ab. (vlt. konfigurierbar machen)
/einzahlen - Zahlt sämtliches Geld von der Hand in den ATM ein

Karma Anzahl hinter + / - Karma Nachricht - Erleichterte Sicht auf das eigene Karma
Veränderte HQ Nachrichten - Verkürzte, informationslastigere HQ Nachrichten (sehr viel vom Staat genutzt)

**Comment by Dimiikou** [comment]
@rettichlp passen all diese Features für dich?

**Comment by rettichlp** [comment]
@Dimiikou bis auf die HQ Nachrichten ja, wäre cool wenn es für die einen Config Eintrag gibt :)
