### ISSUE TITLE
UCAF - Idea for 4 modules

### ISSUE THREAD

**Issue by Gelegenheitscode** [rettichlp/UnicacityAddon-1.12.2#112]
**Aus welchem Grund ist die Idee oder Erweiterung hilfreich?**
- [x] #115

- [x] Durst Modul - Beim join auf Uc wird /health ausgeführt und geschaut wieviel Durst vorhanden ist. Dann wird in einem gewissen Zeitraum immer wieder abgefragt wieviel der Durststand ist. Es ist praktisch, da man so verhindern kann, das man unnötig verdurstet.

- [x] Bargeld Modul - Beim joinen auf UC wird das bargeld bei /stats ausgefragt, und im Spiel wird bei Pay-Nachrichten oder den "-XY$" nachrichten das Geld abgezogen/hinzugefügt. Das ist praktisch, da man so einen besseren Überblick hat.

- [x] Bankgeld Modul - Beim ersten Klick auf ein ATM Schild wird das Modul angezeigt und wird dann bei Abbuchungsnachrichten, Einzahlungsnachrichten, Überweisungen etc. aktualisiert. Das ist praktisch, da man so einen besseren Überblick hat.

**Was soll passieren, wie soll die Idee oder Erweiterung umgesetzt werden?**
- s.o.

**Sonstiges**
Modul 1 Vorschlag: PayDay - XY Minuten (wenn 5 min vor payday wird die anzeige rot)
Modul 2 Vorschlag: Durst - XY.Z/20.0
Modul 3 und 4 Vorschlag: Bar-/Bankgeld: XY$

**Comment by rettichlp** [comment]
Diese Ideen sind uns auch schon gekommen. Wir würden diese aber anders umsetzen. Dafür würden wir gern mit einem weiteren Entwickler zusammenarbeiten.

**Comment by rettichlp** [comment]
**Branches:**
`feature/UCAF-112-1-Payday-module`
`feature/UCAF-112-2-Thirst-module`
`feature/UCAF-112-3-Cash-module`
`feature/UCAF-112-4-Bankbalance-module`

**Comment by rettichlp** [comment]
Bzgl. Durst Modul: Es gibt eine Nachricht im Chat die einem sagt, dass man Durst hat. Ich weiß jetzt nicht wie man unnötig verdursten kann...

**Comment by rettichlp** [comment]
![image](https://user-images.githubusercontent.com/97811064/183308156-44cde715-d11f-4bf2-98f3-f1e51101d3aa.png)

**Comment by rettichlp** [comment]
PayDay Modul -> extra Issue (Grund: [hier](https://github.com/rettichlp/UnicacityAddon-1.12.2/issues/112#issuecomment-1207186467))
