### ISSUE TITLE
Custom Blacklist, hiii dimiikouu :3

### ISSUE THREAD

**Issue by mjjchael** [rettichlp/UnicacityAddon-1.12.2#116]
**Aus welchem Grund ist die Idee oder Erweiterung hilfreich?**
verschiedene Fraktionen haben verschiedene Killanzahlen, Blacklist Gründe & Preise 

**Was soll passieren, wie soll die Idee oder Erweiterung umgesetzt werden?**
Eine klare und präzise Beschreibung dessen, was passieren soll.
Man sollte diese Punkte in einem Menü bearbeiten können 
Killanzahl
Preis
(vielleicht auch noch einen benutzerdefinierten Grund, da die meisten bl namen in manchen fraktionen ja auch in der jeweiligen sprache sind)

**Sonstiges**
Füge hier jeglichen anderen Kontext oder Screenshots zur Funktionsanfrage hinzu.

**Comment by rettichlp** [comment]
Das erinnert mich daran, das Wiki zu erweitern :D

**Comment by rettichlp** [comment]
[https://github.com/rettichlp/UnicacityAddon-1.12.2/wiki/ASetBlacklistCommand](https://github.com/rettichlp/UnicacityAddon-1.12.2/wiki/ASetBlacklistCommand)
