### ISSUE TITLE
UCAF - Füge hier eine kurze Beschreibung ein

### ISSUE THREAD

**Issue by icedemlo** [rettichlp/UnicacityAddon-1.12.2#118]
**Aus welchem Grund ist die Idee oder Erweiterung hilfreich?**
Es erleichtert Spielern die jobben.

**Was soll passieren, wie soll die Idee oder Erweiterung umgesetzt werden?**
Ein Payday Timer, diesen so integrieren wie mit dem Job Gehalt. Damit man weiß wie lange man noch hat bis der Payday zu Ende geht.

**Comment by Dimiikou** [comment]
done in #115

**Comment by icedemlo** [comment]
> done in #117

Sprich in der Version 1.1.7?

**Comment by Dimiikou** [comment]
> > done in #117
> 
> 
> 
> Sprich in der Version 1.1.7?
> 
> 

In der 1.2.0 dann

**Comment by icedemlo** [comment]
> > > done in #117
> > 
> > 
> > Sprich in der Version 1.1.7?
> 
> In der 1.2.0 dann

okay, danke
