### ISSUE TITLE
Automatisches Kaufen

### ISSUE THREAD

**Issue by icedemlo** [rettichlp/UnicacityAddon-1.12.2#119]
**Aus welchem Grund ist die Idee oder Erweiterung hilfreich?**
Automatisches Kaufen

**Was soll passieren, wie soll die Idee oder Erweiterung umgesetzt werden?**
/abuy [Menge] und mit einem Hotkey dies das im Shop ausführen, dann muss man nicht immer einzeln klicken

**Comment by Dimiikou** [comment]
duplicate with #43
