### ISSUE TITLE
UCAF - House renter management

### ISSUE THREAD

**Issue by Xiiiro** [rettichlp/UnicacityAddon-1.12.2#128]
**Aus welchem Grund ist die Idee oder Erweiterung hilfreich?**
Momentan sieht es so aus wenn man /mieters eingibt (https://i.imgur.com/NZeMWQZ.png), dies kann bei vielen Häusern und vielen Mietern etwas unübersichtlich und verwirrend sein, da es schwer ist direkt zu sehen welcher Mieter inaktiv ist (zum Beispiel schon mehr als 3 Tage offline) und nicht immer leicht zu zählen wie viele Mieter gerade in einem Haus wohnen ohne dies selbständig immer zu zählen.
**Was soll passieren, wie soll die Idee oder Erweiterung umgesetzt werden?**
Eine klare und präzise Beschreibung dessen, was passieren soll.
- [ ] Wenn man den /mieters command eingibt, werden die Daten ausgelesen die dort stehen. Anschließend bekommt man im Chat eine Nachricht von der Mod, wo aufgelistet wird, wie viele Mieter in den jeweiligen Häusern wohnen und welcher Mieter in welchem Haus schon mehr als z.B. 3 Tage (Anzahl der Tage kann man vlt in den Mod-Optionen verändern) offline war.

**Sonstiges**
/

**Comment by rettichlp** [comment]
Ich stell mir das etwa so vor:
![image](https://user-images.githubusercontent.com/97811064/184188584-d6ac59cf-96b8-4e0b-950d-fe7c6950962e.png)
