### ISSUE TITLE
UCAB - Wrong item for own-use-drugs

### ISSUE THREAD

**Issue by mjjchael** [rettichlp/UnicacityAddon-1.12.2#131]
**Beschreibe den Bug oder Fehler**
Eine klare und präzise Beschreibung des Fehlers.

**Wie kann der Bug oder Fehler reproduziert werden?**
Schritte zum Reproduzieren des Verhaltens:
1. Gehen zu "Eigenbedarf"
2. Klicke auf "Gras"
4. Dort ist der Fehler

**Erwartetes Verhalten**
Wenn man beim Eigenbedarf Menü, Gras anklickt, wird bei dir benutzerdefinierten Menge, die Koks Textur angezeigt

**Screenshots**
https://prnt.sc/d-R6qHY2WOIW

**Weitere Informationen (bitte ausfüllen):**
Minecraft Version: `1.12.2`
Addon Version: `1.2.0`

**Comment by rettichlp** [comment]
Danke fürs Melden :)

**Comment by Dimiikou** [comment]
Behoben in #133
