### ISSUE TITLE
UCAF - Equip counter

### ISSUE THREAD

**Issue by Gelegenheitscode** [rettichlp/UnicacityAddon-1.12.2#132]
**Aus welchem Grund ist die Idee oder Erweiterung hilfreich?**
Man hat einen Überblick über seine Equipkosten und die equippten Dinge der Woche, um fraktionsinterne Strafen zu vermeiden.

**Was soll passieren, wie soll die Idee oder Erweiterung umgesetzt werden?**
Man kann in der Config Equip items einstellen, mit Namen und Preis.
Bei der Equip-Nachricht ([Equip] Du hast dir XY equippt.) wird dies gesichert und eingetragen.
Mit /equipinfo kann man dann sehen (Beispiel unten) wieviel man je von den in der Config eingestellten Items equippt hat, und daneben der Preis. Mit /clearequipinfo kann man diese Liste am Ende der Woche dann löschen.

**Sonstiges**
Bsp.: 
=== Equip Info ===
2x Schmerzpillen - 160$
1x Spritze - 120$
5x Bandage - 400$
Insg.: 680$

**Comment by rettichlp** [comment]
Wird erstmal hinten an gestellt wegen [dieses](https://forum.unicacity.de/index.php?thread/97131-eigenes-equip-sehen/) Forum-Vorschlags

**Comment by Gelegenheitscode** [comment]
> Wird erstmal hinten an gestellt wegen [dieses](https://forum.unicacity.de/index.php?thread/97131-eigenes-equip-sehen/) Forum-Vorschlags

Fände es trotzdem praktischer als der Vorschlag im Forum, da man so auch sieht, was man equippt hat 🤔
