### ISSUE TITLE
UCAF - Cooldown for Tazer Warning

### ISSUE THREAD

**Issue by Dimiikou** [rettichlp/UnicacityAddon-1.12.2#134]
**Aus welchem Grund ist die Idee oder Erweiterung hilfreich?**
Zwischen den einzelnen Nachrichten des Tazer Warners sollte es einen Cooldown geben.
Dieser ist dafür da um den Chatspam zu verhindern welcher durch das halten von Linksklick entsteht

**Was soll passieren, wie soll die Idee oder Erweiterung umgesetzt werden?**
Eine klare und präzise Beschreibung dessen, was passieren soll.
- [ ] Cooldown für Tazerwarnen implementieren

**Sonstiges**
Das Problem:
![Tazerspam](https://i.imgur.com/MlChwN2.png)

**Comment by rettichlp** [comment]
Bei einem Linksklick, wird das ja geschickt... ich würde das dazu ändern, dass das bei einem Linksklick geschickt wird, aber nur wenn das Item eine Waffe ist... macht das Sinn?

**Comment by Gelegenheitscode** [comment]
> Bei einem Linksklick, wird das ja geschickt... ich würde das dazu ändern, dass das bei einem Linksklick geschickt wird, aber nur wenn das Item eine Waffe ist... macht das Sinn?

Ich finds gut
