### ISSUE TITLE
UCAF - Explosive belt timer

### ISSUE THREAD

**Issue by Dimiikou** [rettichlp/UnicacityAddon-1.12.2#14]
**Aus welchem Grund ist die Idee oder Erweiterung hilfreich?**
Ein Chat Countdown welcher anzeigt, in wie viel Sekunden der eigene Sprenggürtel explodiert.
Angepasst an den Befehl, gut als Unterstützung der Terror Fraktion

**Was soll passieren, wie soll die Idee oder Erweiterung umgesetzt werden?**
- [x] /sprenggürtel command überschreiben
- [x] Command registrieren

**Sonstiges**

**Comment by rettichlp** [comment]
⚠️ Issue umbenennen @Dimiikou -> `UCAF - Explosive belt timer`

**Comment by rettichlp** [comment]
Ähnlich wie:
- https://github.com/rettichlp/UnicacityAddon-1.12.2/blob/develop/src/main/java/com/rettichlp/UnicacityAddon/events/BombTimerEventHandler.java
- https://github.com/rettichlp/UnicacityAddon-1.12.2/blob/develop/src/main/java/com/rettichlp/UnicacityAddon/modules/BombTimerModule.java

(Nicht vergessen: Config erweitern sowie Modul und Event registrieren)
