### ISSUE TITLE
UCAF - /memberinfo with tabcompletion

### ISSUE THREAD

**Issue by shinshin69** [rettichlp/UnicacityAddon-1.12.2#143]
**Aus welchem Grund ist die Idee oder Erweiterung hilfreich?**
Da dies eine Möglichkeit wäre Zeit zu sparen und nicht immer /memberinfo (Fraktion) eingeben zu müssen

**Was soll passieren, wie soll die Idee oder Erweiterung umgesetzt werden?**
Ersetze den command /memberinfo mit /(Fraktionskürzel)
- statt /memberinfo kerzakov = /kf
- statt /memberinfo mafia = /maf
- statt /memberinfo ucpd = /ucpd
- statt /memberinfo fbi = /fbi
- statt /memberinfo terroristen = /terror
- statt /memberinfo hitman = /hit
- statt /memberinfo ballas = /ballas
- statt /memberinfo triaden = /triad
- statt /memberinfo medic = /med

**Sonstiges**
-

**Comment by rettichlp** [comment]
Ich finde dafür extra Commands etwas viel, was hälst du davon, wenn wir einen /frakinfo Befehl machen mit Tabbaren Fraktionen?

**Comment by shinshin69** [comment]
Das wär krass--Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 12.08.22, 23:34 schrieb RettichLP ***@***.***>:

   
  Ich finde dafür extra Commands etwas viel, was hälst du davon, wenn wir einen /frakinfo Befehl machen mit Tabbaren Fraktionen?
