### ISSUE TITLE
UCAF - Point in the money gui

### ISSUE THREAD

**Issue by Xiiiro** [rettichlp/UnicacityAddon-1.12.2#145]
**Beschreibe den Bug oder Fehler** 
Bei dem Kontostand und wahrscheinlich auch Bargeld und Gehalt von Jobs, fehlt bei der tausender Stelle ein Punkt (https://i.imgur.com/mTpyZYv.png), es steht also 93840$ und nicht 93.840$.

**Wie kann der Bug oder Fehler reproduziert werden?**
Einfach beim GUI aufs Geld schauen.

**Erwartetes Verhalten**
Dass dort 93.840$ statt 93840$ steht und dies dann auch beim Bargeld und Gehalt von Jobs.

**Screenshots**
/

**Weitere Informationen (bitte ausfüllen):**
Minecraft Version: 1.12.2
Addon Version: 1.2.0

**Comment by rettichlp** [comment]
Kein Bug, war genau so gewollt, wir schieben das mit auf die Feature Liste :)
