### ISSUE TITLE
UCAF - /checkactivemembers

### ISSUE THREAD

**Issue by selterss** [rettichlp/UnicacityAddon-1.12.2#146]
**Aus welchem Grund ist die Idee oder Erweiterung hilfreich?**
Der Befehl soll ins Add-On, weil es überlebenswichtig für GN´s oder generell Fraktionen ist.

**Was soll passieren, wie soll die Idee oder Erweiterung umgesetzt werden?**
So wie bei UCutils, man soll einfach sehen wieviele von jeder Fraktion Anwesend sind.

**Sonstiges**
Würde mich sehr über dieses Feature freuen.
LG. Alpazaurier

**Comment by rettichlp** [comment]
Ich würde das mit #143 kombinieren :D
