### ISSUE TITLE
/blinfo

### ISSUE THREAD

**Issue by qhamma** [rettichlp/UnicacityAddon-1.12.2#159]
Es wäre gut weil man nicht in der /bl liste suchen muss sondern man kann gezielt nach der BL einer Person schauen

man gibt /blinfo [Name] ein
und dann zeigt es die Bl der person nach der man gesucht hat im Chat
wie bei UCUtils machen

**Comment by Dimiikou** [comment]
duplicate with #154 
Kommt im nächsten release, ist schon fertig
