### ISSUE TITLE
UCAF - /screen Addon

### ISSUE THREAD

**Issue by ralogithub** [rettichlp/UnicacityAddon-1.12.2#174]
**Aus welchem Grund ist die Idee oder Erweiterung hilfreich?**
Damit man als Staatler einfacher Screens sortieren kann im /screenshots folder!

**Was soll passieren, wie soll die Idee oder Erweiterung umgesetzt werden?**
Wenn man ingame /screen (%alias%) macht, dann wird der Screenshot im minecraft/screenshots Ordner
in den %alias% direkt umbenannt, so muss man nicht auf jeden Screen bei der Sortierung klicken!

**Sonstiges**
/

**Comment by Dimiikou** [comment]
Eine Liste mit paar Aliasen wäre nice damit wir uns da lang hangeln können
