### ISSUE TITLE
UCAF - [AFK] before the Nametag

### ISSUE THREAD

**Issue by DeLott** [rettichlp/UnicacityAddon-1.12.2#182]
**Aus welchem Grund ist die Idee oder Erweiterung hilfreich?**
Damit man weiß wenn eine Person in deinem Umfeld AFK ist und man nicht /id benutzen muss

**Was soll passieren, wie soll die Idee oder Erweiterung umgesetzt werden?**
[AFK] vor dem Nametag einer Person oder einen farbigen Namen für diese Personen

**Sonstiges**
/

**Comment by rettichlp** [comment]
Der einzige Weg um zu überprüfen, ob eine Person AFK ist, geht über `/id`. Um die Idee umzusetzen, müssten wir jedes mal, wenn das `PlayerEvent.NameFormat` Event ausgeführt wird, den oben genannten Befehl ausführen. Das Event wird immer gestartet, wenn ein Spieler in deiner Render-Distance "erscheint". Verlässt der Spieler den Bereich und betritt ihn wieder, würde erneut `/id` ausgeführt werden. Das würde zu FPS Einbrüchen beim Client (dem Spieler) und zu einem sehr hohen Traffic serverseitig führen.

Stell dir vor, wir sind bei einem Community-Screen. Dort sind bereits 100 Spieler und ein weiterer läuft dorthin. Irgendwann ist dieser eine Spieler in der Render-Distance der anderen 100. In Folge dessen, wird bei den 100 bereits anwesenden Spielern die ID des einen Spielers gecheckt und bei dem einen Spieler die 100 IDs der bereits vorhandenen Spieler. Das wären 200 Befehle im Bruchteil einer Sekunde.

Da es jedoch den Spam Schutz gibt, überprüfen zwar die 100 vorhandenen Spieler die ID des neuen Spielers, aber der neue Spieler kann nicht 100 IDs überprüfen und müsste immer 1 Sekunde dazwischen warten. Nach 100 Sekunden hätte der neue Spieler alle alten Spieler abgecheckt aber in der Zeit kamen wieder neue Spieler dazu. Es wäre eine endlose Schleife an IDs die im Sekundentakt überprüft werden.

Aus diesem Grund wird dieses Feature höchstens dann kommen, wenn durch Unicacity eine API Schnittstelle existiert, die alle AFK Spieler anzeigt.

**Comment by rettichlp** [comment]
@Dimiikou fyi 👀
