### ISSUE TITLE
UCAB - ADropMoney still not working well

### ISSUE THREAD

**Issue by Dimiikou** [rettichlp/UnicacityAddon-1.12.2#200]
**Beschreibe den Bug oder Fehler**
Teilweise wird das Geld weiterhin nicht eingezahlt

**Wie kann der Bug oder Fehler reproduziert werden?**
Schritte zum Reproduzieren des Verhaltens:
1. Geldtransport Job
2. An ATM stellen
3. /adropmoney

**Erwartetes Verhalten**
Geld wird abgehoben, /dropmoney, Geld wird wieder eingezahlt

**Screenshots**
/

**Weitere Informationen (bitte ausfüllen):**
Minecraft Version: `1.12.2`
Addon Version: `1.3.1`

**Comment by Dimiikou** [comment]
> geht für mich

weird, ich beobachte es mal weiter!

**Comment by rettichlp** [comment]
![image](https://user-images.githubusercontent.com/97811064/185239522-45091ac5-16fe-4474-ae66-83c47faef38c.png)

**Comment by rettichlp** [comment]
Cooldown von 1000ms auf 1500ms erhöht, schauen ob es jetzt klappt...
