### ISSUE TITLE
UCAF - Aktienhelper

### ISSUE THREAD

**Issue by eyyJustvs** [rettichlp/UnicacityAddon-1.12.2#214]
**Aus welchem Grund ist die Idee oder Erweiterung hilfreich?**
Um den Aktienmarkt übersichtlicher zu gestalten.

**Was soll passieren, wie soll die Idee oder Erweiterung umgesetzt werden?**
Im "/aktienmarkt"-Interface soll hinter den Aktien die man hält stehen für wieviel man diese mit Bankverarbeitungskosten insgesammt gezahlt hat. Des weiteren soll dann Anhand vom Aktuellen Preis der Aktie errechnet werden, für wieviel man jetzt mit dem Verkauf bekommen würde. (Als aller letztes wäre es natürlich cool, wenn die Differenz zwischen den 2 Werten ausgerechnet wird, damit man sieht wieviel plus/minus man mit dem Verkauf der Aktie machen würde. Ist aber nicht so wichtig wie die beiden oberen)

**Comment by rettichlp** [comment]
Ich bring erstmal eine kleine Hilfe ins Spiel, weil ich bald im Urlaub bin und somit erstmal etwas kleines habe... Das Feature wird sicher noch viel cooler, aber erst nach dem Urlaub :)
