### ISSUE TITLE
Fbank

### ISSUE THREAD

**Issue by Tommy512JJ** [rettichlp/UnicacityAddon-1.12.2#221]
Wenn man geld in die F Bank einzahlt zeigt es sich immernoch bei bargeld an

**Comment by rettichlp** [comment]
Hallo,
um Dir bestmöglich zu helfen, benötigen wir mehr Informationen. Dazu zählen zum Beispiel Deine verwendete Minecraft Version, Addon Version und Minecraft Log oder Absturzbericht.
Halte Dich bitte an die von uns bereitgestellte Vorlage. Dadurch kannst Du keine relevanten Informationen vergessen.
Für schnelle Hilfe kannst Du auch gern auf unseren Discord joinen.

**Comment by rettichlp** [comment]
Aufgrund fehlender weiterer Informationen und keiner gefundener Fehler, kann dieses Issue nicht weiter verfolgt werden.
