### ISSUE TITLE
UCAB - Typo in reinforcement hover message

### ISSUE THREAD

**Issue by rettichlp** [rettichlp/UnicacityAddon-1.12.2#23]
**Beschreibe den Bug oder Fehler**
Schreibfehler

**Wie kann der Bug oder Fehler reproduziert werden?**
- [x] Reinforcement: Unterwegs Hover Nachricht steht "nachricht" statt "Nachricht"

**Erwartetes Verhalten**
- "nachricht" statt "Nachricht"

**Screenshots**
![image](https://user-images.githubusercontent.com/97811064/180231693-75ab2bd5-7bb3-4aea-9929-6956ba5a4bac.png)

**Weitere Informationen (bitte ausfüllen):**
Minecraft Version: `1.16.5`
Addon Version: `1.0.0-beta`

**Comment by Dimiikou** [comment]
Fixed in: https://github.com/rettichlp/UnicacityAddon-1.12.2/commit/d6601e6517a8556a74fe9d8ff7e793dd64c659c1
