### ISSUE TITLE
UCAF - Service Counter

### ISSUE THREAD

**Issue by Gelegenheitscode** [rettichlp/UnicacityAddon-1.12.2#251]
**Aus welchem Grund ist die Idee oder Erweiterung hilfreich?**
Man muss am ende der woche nicht seinen Leader fragen, wieviele Services man hat, und man kann seine Mindestaktivität besser planen.

**Was soll passieren, wie soll die Idee oder Erweiterung umgesetzt werden?**
Zählt die Services anhand der "Du hast den Service von XY als erledigt makiert." nachricht und man kann es mit /serviceinfo abrufen.

**Sonstiges**
///

**Comment by rettichlp** [comment]
@Gelegenheitscode Services, Revives oder beides?

**Comment by Gelegenheitscode** [comment]
Services, sorry hab mich vertan
