### ISSUE TITLE
UCAF - Statistics

### ISSUE THREAD

**Issue by Dimiikou** [rettichlp/UnicacityAddon-1.12.2#255]
**Aus welchem Grund ist die Idee oder Erweiterung hilfreich?**
Nutzerzahlen etc. sollten gesammelt werden und als Information einsehbar

**Was soll passieren, wie soll die Idee oder Erweiterung umgesetzt werden?**
Rettich weiß das schon :D 

**Sonstiges**
/

**Comment by rettichlp** [comment]
blocked by #254
