### ISSUE TITLE
UCAF - /dropzeitung on rightclick at house sign

### ISSUE THREAD

**Issue by Dimiikou** [rettichlp/UnicacityAddon-1.12.2#257]
**Aus welchem Grund ist die Idee oder Erweiterung hilfreich?**
Der Job Zeitungsjunge wird aufs unendliche vereinfacht. Durch ein einfaches Klicken auf das Hausschild erspart man sich eine Menge Zeit

**Was soll passieren, wie soll die Idee oder Erweiterung umgesetzt werden?**
Eine klare und präzise Beschreibung dessen, was passieren soll.
- [ ] Event Listener erstellen

**Sonstiges**
/

**Comment by rettichlp** [comment]
💡 /getwaste
