### ISSUE TITLE
UCAB - Füge hier eine kurze Beschreibung ein

### ISSUE THREAD

**Issue by icedemlo** [rettichlp/UnicacityAddon-1.12.2#268]
**Beschreibe den Bug oder Fehler**
/tsjoin [Channel], leider funktioniert dieser Befehl nicht als Hotkey
![image](https://user-images.githubusercontent.com/110923195/190902250-91800551-9689-4f8f-b7a6-add63e62de06.png)

Sobald ich meinen Hotkey drücke höre ich zwar den Sound das ich etwas gedrückt habe aber passiert leider nichts.

**Erwartetes Verhalten**
Das man einfach in den Channel joint (Gut fürs Öffiteam)

**Weitere Informationen (bitte ausfüllen):**
Minecraft Version: `1.16.5`
Addon Version: `1.4.0`

**Comment by Dimiikou** [comment]
Hey Emlo,
Ich verstehe das dich das stört. jedoch ist das leider kein Fehler an dem wir direkt arbeiten können.
Über deinen Hotkey wird der Befehl `/tsjoin Öffentlich` automatisch direkt an den Server geschickt. Da dieser Befehl aber nur von deinem Client erkannt und verwendet werden kann, wird dieser nie ausgeführt da der Client einfach übersprungen wird.

Ich bespreche aber mal von Rettich ob wir dafür einen eigenen Hotkey erstellen wollen!

Mit freundlichen Grüßen
Dimiikou

**Comment by rettichlp** [comment]
Wir könnten allerdings einen Hotkey von uns festlegen (wie für ABuy oder Screenshots) :)

**Comment by rettichlp** [comment]
Issue #269
