### ISSUE TITLE
UCAF - Hotkey for ts join public channel

### ISSUE THREAD

**Issue by rettichlp** [rettichlp/UnicacityAddon-1.12.2#269]
**Aus welchem Grund ist die Idee oder Erweiterung hilfreich?**
Schneller in den Öffentlich kommen

**Was soll passieren, wie soll die Idee oder Erweiterung umgesetzt werden?**
Nach dem Drücken des Hotkeys soll `/tsjoin Öffentlich` gesendet werden

**Sonstiges**

**Comment by Gelegenheitscode** [comment]
hotkey für reinforcement auch aus selben grund

reinf type kann man dann in config aussuchen für den hotkey

**Comment by Dimiikou** [comment]
> hotkey für reinforcement auch aus selben grund
> 
> reinf type kann man dann in config aussuchen für den hotkey

Mach mal ein neues Issue dafür
