### ISSUE TITLE
UCAB - Commands work without prefix

### ISSUE THREAD

**Issue by Dimiikou** [rettichlp/UnicacityAddon-1.12.2#276]
**Beschreibe den Bug oder Fehler**
Wenn man nur den Befehlnamen ohne / eingibt wird der Befehl trotzdem ausgeführt.

**Wie kann der Bug oder Fehler reproduziert werden?**
Schritte zum Reproduzieren des Verhaltens:
1. Gib einen Command Namen ohne Prefix in den RP Chat ein

**Erwartetes Verhalten**
Command wird nicht ausgeführt.

**Screenshots**
/

**Weitere Informationen (bitte ausfüllen):**
Minecraft Version: `1.12.2`
Addon Version: `1.5.0-dev`

**Comment by rettichlp** [comment]
https://forums.minecraftforge.net/topic/64820-command-executes-without-backslash/
