### ISSUE TITLE
UCAF - hotkey für reinforcement auch aus selben grund

### ISSUE THREAD

**Issue by Gelegenheitscode** [rettichlp/UnicacityAddon-1.12.2#284]
hotkey für reinforcement auch aus selben grund

reinf type kann man dann in config aussuchen für den hotkey

_Originally posted by @Gelegenheitscode in https://github.com/rettichlp/UnicacityAddon-1.12.2/issues/269#issuecomment-1252638338_

**Comment by rettichlp** [comment]
@Gelegenheitscode Du wolltest ja auch mal programmieren... Das ist eigentlich recht einfach. Tob dich gern mal an diesem Issue aus :)
