### ISSUE TITLE
UCAF - Le Milieu

### ISSUE THREAD

**Issue by rettichlp** [rettichlp/UnicacityAddon-1.12.2#288]
**Aus welchem Grund ist die Idee oder Erweiterung hilfreich?**

**Was soll passieren, wie soll die Idee oder Erweiterung umgesetzt werden?**
- [x] FDoor
- [x] TS Public Channel
- [x] Faction List (&3 - dark aqua, ☕)
- [ ] Member (?)
- [x] ATM (59?)

**Sonstiges**

**Comment by rettichlp** [comment]
![img](https://cdn.discordapp.com/attachments/1008929806919925891/1024602771049152522/Minecraft_1.12.2___LabyMod_3.9.46_28.09.2022_10_38_40.png)

**Comment by Dimiikou** [comment]
blocked by #254
