### ISSUE TITLE
UCAB - Nullpointer exception in tsfind

### ISSUE THREAD

**Issue by Dimiikou** [rettichlp/UnicacityAddon-1.12.2#348]
**Beschreibe den Bug oder Fehler**
Teilweise kann bei /tsfind eine Nullpointer Exception entstehen.

**Wie kann der Bug oder Fehler reproduziert werden?**
Schritte zum Reproduzieren des Verhaltens:
1. /tsfind Name
2. Ich weiß auch nicht man

**Erwartetes Verhalten**
Es geht

**Screenshots**
https://paste.labymod.net/equnederag.apache

**Weitere Informationen (bitte ausfüllen):**
Minecraft Version: `1.12.2`
Addon Version: `1.5.0`

**Comment by rettichlp** [comment]
Instance von TSClientQuery wurde nicht geladen -> Fehler

Sollte nicht erneut auftreten...
