### ISSUE TITLE
UCAF - Duty tag in nametag

### ISSUE THREAD

**Issue by yXaver** [rettichlp/UnicacityAddon-1.12.2#37]
**Aus welchem Grund ist die Idee oder Erweiterung hilfreich?**
Man kann immer sehen wer In/Off-Duty ist und dies macht viele Dinge einfacher, z.B. für Bad-Frakler Leute zum Ausrauben zu finden

**Was soll passieren, wie soll die Idee oder Erweiterung umgesetzt werden?**
- [x] Ein Rotes Symbol wenn die Person nicht im Duty ist
- [x] Ein Grünes Symbol wenn die Person im Duty ist

**Comment by rettichlp** [comment]
Wie bereits im Unicacity Forum erwähnt:
> Das wäre bei FBI/Cops/Medics möglich, bei den anderen Fraktionen würde das mehr Performance ziehen als es Vorteil bringt

Durch die sortierte Tabliste (#12) ist es möglich schnell alle aktiven Member der genannten Fraktionen zu sehen. Ich weiß nicht wie es andere sehen, aber aktuell sehe ich noch keinen Grund für dieses Feature...

**Comment by Gelegenheitscode** [comment]
Finde ich schon praktisch, vor allem als Terror/Badfrakler um bei GN's/Bomben schnell Staatler zu sehen, die nicht im Dienst sind.

**Comment by rettichlp** [comment]
Ich war noch nicht in einer Badfrak, aber warum wäre das wichtig zu sehen?

**Comment by Dimiikou** [comment]
> Ich war noch nicht in einer Badfrak, aber warum wäre das wichtig zu sehen?

Der Staat darf Off Duty kaum bis garnicht gegen uns agieren, ebenso dürfen Cops welche nicht im Duty sind nicht erschossen werden. Ist schon Sinnvoll das schnell zu erkennen. Hatte aber nie Probleme damit das es für mich zu schwer wäre zu erkennen, dieses Punkt feature wäre aber trotzdem relativ lustig

**Comment by rettichlp** [comment]
![image](https://user-images.githubusercontent.com/97811064/180741482-8e7652f7-f271-4d25-a05c-db8fd8f06f47.png)

**Comment by rettichlp** [comment]
Ich habe jetzt nur einen Punkt dahinter, wenn derjenige im Dienst ist, reicht der oder sind rot und grün besser?

**Comment by Gelegenheitscode** [comment]
rot besser

**Comment by rettichlp** [comment]
Nur rot oder rot für offduty und grün für duty?

**Comment by Gelegenheitscode** [comment]
ja das was du sagst
