### ISSUE TITLE
UCAF - Automate finish of services

### ISSUE THREAD

**Issue by Gelegenheitscode** [rettichlp/UnicacityAddon-1.12.2#374]
**Aus welchem Grund ist die Idee oder Erweiterung hilfreich?**
Services werden automatisch gefinished beim erreichen des navipunkts

**Was soll passieren, wie soll die Idee oder Erweiterung umgesetzt werden?**
Eine klare und präzise Beschreibung dessen, was passieren soll.
- [x] config eintrag zum toggeln erstellen
- [x] pattern erstellen

**Sonstiges**

**Comment by rettichlp** [comment]
Find ich gut, aber ich möchte noch einen Check haben ob der richtige Navipunkt erreicht wurde und nicht der von zum Beispiel `/car find` :)

**Comment by rettichlp** [comment]
@Gelegenheitscode Wo ist hier was completed?! Das Issue ist höchstes `Close as not planned` aber nicht `completed`!
