### ISSUE TITLE
UCAF - Advanced broadcast command

### ISSUE THREAD

**Issue by rettichlp** [rettichlp/UnicacityAddon-1.12.2#399]
**Aus welchem Grund ist die Idee oder Erweiterung hilfreich?**
Um den Broadcast auch vom Spiel aus zu senden, ist es hilfreich den Command dafür anzupassen

**Was soll passieren, wie soll die Idee oder Erweiterung umgesetzt werden?**
- [ ] Tabbares Datum und Urzeit
- [ ] Broadcast Nachricht anpassen

**Sonstiges**

**Comment by Kraaut** [comment]
Team Broadcast fehlt!

**Comment by Kraaut** [comment]
grrrr
