### ISSUE TITLE
UCAF - Display ammunition count in ActionBar

### ISSUE THREAD

**Issue by Dimiikou** [rettichlp/UnicacityAddon-1.12.2#41]
**Aus welchem Grund ist die Idee oder Erweiterung hilfreich?**
Die Restliche Munition einer Waffe sollte in der Actionbar angezeigt werden.
Dies ist wichtig um einen überblick über seine übrigen Schuss zu haben.

**Was soll passieren, wie soll die Idee oder Erweiterung umgesetzt werden?**
Eine klare und präzise Beschreibung dessen, was passieren soll.
- [ ] Restliche Munition tracken
- [ ] Anzeige über Hotbar erstellen und bei jedem Schuss (Rechtsklick mit Waffe) aktualisieren

**Sonstiges**
Maximale Munition muss aus der Lore der jeweiligen Waffe ausgelesen werden.

**Comment by rettichlp** [comment]
Ich würde das eher als Modul machen, dass dann jeder die Anzeige dahin schieben kann wo er möchte :)

**Comment by Dimiikou** [comment]
> Ich würde das eher als Modul machen, dass dann jeder die Anzeige dahin schieben kann wo er möchte :)

Gefällt mir😎
