### ISSUE TITLE
UCAF - FDoor shortcut

### ISSUE THREAD

**Issue by Dimiikou** [rettichlp/UnicacityAddon-1.12.2#42]
**Aus welchem Grund ist die Idee oder Erweiterung hilfreich?**
Mittels einem Rechtsklick auf die Fraktionstüren (Gittertore etc.) wird der Befehl /fdoor ausgeführt.

**Was soll passieren, wie soll die Idee oder Erweiterung umgesetzt werden?**
Eine klare und präzise Beschreibung dessen, was passieren soll.
- [ ] Listener, welcher /fdoor ausführt sobald ein Tor gerechtsklickt wurde

**Sonstiges**

**Comment by ImKxvin12** [comment]
selbe für kf wäre baba

**Comment by Dimiikou** [comment]
> selbe für kf wäre baba

Wird dann direkt mit eingebunden, sämtliche Fraks
