### ISSUE TITLE
UCAF - Message on public Channel join

### ISSUE THREAD

**Issue by Dimiikou** [rettichlp/UnicacityAddon-1.12.2#46]
**Aus welchem Grund ist die Idee oder Erweiterung hilfreich?**
Sollte ein Spieler den Öffentlich Channel betreten soll eine Nachricht im Ingame Chat ausgegeben werden.
Mittels dieser Nachricht soll man in den Channel joinen, oder den Spieler zu sich moven können.

**Was soll passieren, wie soll die Idee oder Erweiterung umgesetzt werden?**
Eine klare und präzise Beschreibung dessen, was passieren soll.
- [ ] Liste aller Öffis zugehörig zu den jeweiligen Fraktionen
- [ ] TS3query Command um in den Öffi joinen zu können
- [ ] TS3query Command um aus dem Öffi moven zu können

**Sonstiges**

**Comment by rettichlp** [comment]
Blocked by #45

**Comment by rettichlp** [comment]
closes by #91
