### ISSUE TITLE
UCAF - Add todo list

### ISSUE THREAD

**Issue by ItsM4rvin** [rettichlp/UnicacityAddon-1.12.2#48]
Wie bei UCUtils /addtodo um Todo listen hinzuzufügen.
/todo um diese Anzuschauen.
/modifytodo um diese zu Bearbeiten.

Auto /todo on Join, (Einstellbar)

**Comment by rettichlp** [comment]
Bitte in Zukunft die Templates nutzen für die Übersichtlichkeit, danke :)
