### ISSUE TITLE
UCAB - Recipe Bug

### ISSUE THREAD

**Issue by Gelegenheitscode** [rettichlp/UnicacityAddon-1.12.2#51]
**Beschreibe den Bug oder Fehler**
Bei /arezept Schmerzmittel XY [Anzahl] wird nach der angegeben Anzahl nicht aufgehört zu verkaufen.

**Wie kann der Bug oder Fehler reproduziert werden?**
Schritte zum Reproduzieren des Verhaltens:
1. /arezept XY Schmerzmittel Y
2. Warten
3. Hört nicht auf zu verkaufen

**Erwartetes Verhalten**
Hört nach der angegebenen Zahl auf zu verkaufen.

**Screenshots**
/

**Weitere Informationen (bitte ausfüllen):**
Minecraft Version: `1.12.2`
Addon Version: `1.0.0`

**Comment by rettichlp** [comment]
Konnte reproduziert werden, wird gefixed, danke fürs Melden
