### ISSUE TITLE
UCAF - Custom Sounds

### ISSUE THREAD

**Issue by Dimiikou** [rettichlp/UnicacityAddon-1.12.2#553]
**Aus welchem Grund ist die Idee oder Erweiterung hilfreich?**
Ist lustig

**Was soll passieren, wie soll die Idee oder Erweiterung umgesetzt werden?**
Eine klare und präzise Beschreibung dessen, was passieren soll.
- [ ] FileManager erstellen

**Sonstiges**

**Comment by rettichlp** [comment]
Ressource Pack mit Template auf Discord - done
