### ISSUE TITLE
UCAF - corruption calculator

### ISSUE THREAD

**Issue by Gelegenheitscode** [rettichlp/UnicacityAddon-1.12.2#609]
**Aus welchem Grund ist die Idee oder Erweiterung hilfreich?**
Zeigt an wieviel Korruptionspreis ein Spieler kostet (FBI Preise)

**Was soll passieren, wie soll die Idee oder Erweiterung umgesetzt werden?**
- [x] Command erstellen

**Sonstiges**
Füge hier jeglichen anderen Kontext oder Screenshots zur Funktionsanfrage hinzu.

**Comment by Gelegenheitscode** [comment]
//assign Gelegenheitscode

**Comment by rettichlp** [comment]
Wie würde sich der Preis berechnen?
