### ISSUE TITLE
UCAF - automated revive screenshot

### ISSUE THREAD

**Issue by Gelegenheitscode** [rettichlp/UnicacityAddon-1.12.2#615]
**Aus welchem Grund ist die Idee oder Erweiterung hilfreich?**
Da medics aktuell keine Mod haben, welche die Revives zählt müssen diese die aktuell manuell abscreenen.
Ein solches Feature würde das vereinfachen.

**Was soll passieren, wie soll die Idee oder Erweiterung umgesetzt werden?**
- [x] Neuen ScreenshotType erstellen
- [x] In ReviveEventHandler einbauen

**Sonstiges**
Füge hier jeglichen anderen Kontext oder Screenshots zur Funktionsanfrage hinzu.

**Comment by rettichlp** [comment]
und warum wird nicht einfach in das Addon integriert dass Revives gezählt werden? Warum muss das als Screenshot gemacht werden?

**Comment by rettichlp** [comment]
Abwarten was mit den Medics noch so passiert

**Comment by rettichlp** [comment]
Revives werden zukünftig anders gezählt.
