### ISSUE TITLE
UCAB - Incompatible with Macro Mod

### ISSUE THREAD

**Issue by Dimiikou** [rettichlp/UnicacityAddon-1.12.2#62]
**Beschreibe den Bug oder Fehler**
Macro Mod und UCA sind inkompatibel. Beim Joinen auf den Server mit beiden stürzt das Spiel ab (auch ohne eingestellte Makros)

https://paste.labymod.net/aserafurac.sql - Fehlermeldung

**Wie kann der Bug oder Fehler reproduziert werden?**
Schritte zum Reproduzieren des Verhaltens:
1. Lightloader Forge usen
2. Macro Mod und UCA usen
3. Server / Singleplayer joinen

**Erwartetes Verhalten**
Erwartet wird, das man ganz normal Joint und glücklich umherspringen kann

**Screenshots**
/

**Weitere Informationen (bitte ausfüllen):**
Minecraft Version: `Lightloader Forge1.12.2`
Addon Version: `1.1.0`

**Comment by rettichlp** [comment]
Bitte testen, ob mit `v1.1.0` das Problem behoben ist :)

**Comment by Dimiikou** [comment]
> Bitte testen, ob mit `v1.1.0` das Problem behoben ist :)

Leider nein

**Comment by rettichlp** [comment]
Fixed with https://github.com/rettichlp/UnicacityAddon-1.12.2/commit/5dbeb03002d1071af6aeb28f7267f0aeeff5576a
