### ISSUE TITLE
UCAF - Rightclick on ATM Sign

### ISSUE THREAD

**Issue by Gelegenheitscode** [rettichlp/UnicacityAddon-1.12.2#67]
**Aus welchem Grund ist die Idee oder Erweiterung hilfreich?**
Man hat eine einfachere Übersicht über die Guthaben und muss nicht gucken wieviel schon eingezahlt wurde, oder einfach zur besseren und schnelleren Information.

**Was soll passieren, wie soll die Idee oder Erweiterung umgesetzt werden?**
Die Nachricht, die beim klicken aufs ATM Schild kommt wird überschrieben, sodass wenn man auf das Schild klickt eine Nachricht bekommt die das Bankkonto, wenn vorhanden das Gruppierungskonto und, wenn vorhanden, den Fraktionsbankstand (evtl. auch wieviel eingezahlt wurde, wegen steuern) anzeigt.

**Sonstiges**

Beispiel:
=== Kontoauszug ===
Bankguthaben: XY
Gruppierungskasse: XY
Fraktionsbank: XY (Z$ bis Steuern)
===============

**Comment by rettichlp** [comment]
Der Fraktions-Kontoauszug besteht aus dem eigentlichen Betrag und der Aufteilung von Ein- und Auszahlung. Somit ist die extra Berechnung nicht notwendig ;)

![Image](https://user-images.githubusercontent.com/97811064/182376769-24118256-a3c3-49e6-bbf0-da131a94279c.png)
