### ISSUE TITLE
UCAB - Faulty navi-point name for KF-Bar

### ISSUE THREAD

**Issue by Dimiikou** [rettichlp/UnicacityAddon-1.12.2#68]
**Beschreibe den Bug oder Fehler**
Bei dem Navipunkt der KF-Bar fehlt ein Leerzeichen.
- aktuell: Kerzakov FamilienBar
- gewollt: Kerzakov Familien Bar
- optional: KF-Bar (wäre kürzer und cooler)

**Wie kann der Bug oder Fehler reproduziert werden?**
Schritte zum Reproduzieren des Verhaltens:
1. Erhalte / mache einen Reinf bei der KF-Bar
2. Fehler in der Chat Nachricht

**Screenshots**
(https://i.imgur.com/rM5vhrS.png)

**Weitere Informationen (bitte ausfüllen):**
Minecraft Version: `1.12.2`
Addon Version: `1.1.0-dev`

**Comment by rettichlp** [comment]
Kein `good first issue`, da die Datei, in der die Änderungen gemacht werden müssen, nicht öffentlich ist

**Comment by rettichlp** [comment]
- Name geändert zu `KF-Bar`
- `x3` Navipunkt hinzugefügt
