### ISSUE TITLE
UCAF - AutoText

### ISSUE THREAD

**Issue by ImNxck** [rettichlp/UnicacityAddon-1.12.2#71]
**Aus welchem Grund ist die Idee oder Erweiterung hilfreich?**
Es erleichtert einem das Connecten und das darauffolgende Ausführen von Befehlen.

**Was soll passieren, wie soll die Idee oder Erweiterung umgesetzt werden?**
- Man soll in der Config Befehle hinzufügen können, die automatisch bei dem Connecten auf einen Server ausgeführt werden

**Sonstiges**
///

**Comment by rettichlp** [comment]
@Dimiikou am besten noch ein ON/OFF Switch/Checkbox einbauen, ob mit der Ausführung des Befehls gewartet werden soll, bis das Passwort eingegeben wurde (bei Bedarf)

**Comment by Dimiikou** [comment]
done in #107
